<a href="https://colab.research.google.com/github/gargiisc/nndl/blob/main/expt5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
w=np.array([1,-1,0,0.5]).transpose()
Xi=[np.array([1,-2,0,-1]).transpose(), np.array([0, 1.5, -0.5, -1]).transpose(), np.array([-1, 1, 0.5, -1]).transpose()]
c=0.1
d=[-1, -1, 1]
i=0

In [6]:
for i in range(len(Xi)):
    net=sum(w.transpose()*Xi[i])
    print("Net: ", net)
    o=np.sign(net)
    print("O: ", o)
    r=d[i]-o
    print("fnet: ", r)
    dw=c*r*Xi[i]
    print(dw)
    w=w+dw
    print('weight vector:',w)
    i+=1

Net:  2.5
O:  1.0
fnet:  -2.0
[-0.2  0.4 -0.   0.2]
weight vector: [ 0.8 -0.6  0.   0.7]
Net:  -1.5999999999999999
O:  -1.0
fnet:  0.0
[ 0.  0. -0. -0.]
weight vector: [ 0.8 -0.6  0.   0.7]
Net:  -2.0999999999999996
O:  -1.0
fnet:  2.0
[-0.2  0.2  0.1 -0.2]
weight vector: [ 0.6 -0.4  0.1  0.5]


In [7]:
print('Final vector: ', w)
print('No. of iterations: ', i)

Final vector:  [ 0.6 -0.4  0.1  0.5]
No. of iterations:  3
