<a href="https://colab.research.google.com/github/gargiisc/nndl/blob/main/SDPTA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
w=np.array([[1,-1,0,0.5]]).T
xi=np.array([[1,-2,0,1], [0,1.5,0.5,-1], [-1,1,0.5,-1]]).T
d=np.array([-1,1,1])
c=0.1
error=-1
i=0
print("Intial Weights: \n", w)

Intial Weights: 
 [[ 1. ]
 [-1. ]
 [ 0. ]
 [ 0.5]]


In [3]:
while error!=0:
  error=0
  for i in range(len(xi.T)):
    net=np.sum(w.T @ xi[:, i])
    print(f"Iteration {i+1}, Sample {i+1}: Net Input: {net:.4f}")
    o=1 if net>=0 else -1
    e=d[i]-o
    error += 0.5*e**2
    dw=c*e*xi[:,i].reshape(-1,1)
    w+=dw
    print(f"Error: {e:.4f}")
    print(f"Updated Weights:\n{w.T}\n")
    i+=1
    if e==0:
      break
  print("\nFinal Weight Matrix:\n", w)

Iteration 1, Sample 1: Net Input: 3.5000
Error: -2.0000
Updated Weights:
[[ 0.8 -0.6  0.   0.3]]

Iteration 2, Sample 2: Net Input: -1.2000
Error: 2.0000
Updated Weights:
[[ 0.8 -0.3  0.1  0.1]]

Iteration 3, Sample 3: Net Input: -1.1500
Error: 2.0000
Updated Weights:
[[ 0.6 -0.1  0.2 -0.1]]


Final Weight Matrix:
 [[ 0.6]
 [-0.1]
 [ 0.2]
 [-0.1]]
Iteration 1, Sample 1: Net Input: 0.7000
Error: -2.0000
Updated Weights:
[[ 0.4  0.3  0.2 -0.3]]

Iteration 2, Sample 2: Net Input: 0.8500
Error: 0.0000
Updated Weights:
[[ 0.4  0.3  0.2 -0.3]]


Final Weight Matrix:
 [[ 0.4]
 [ 0.3]
 [ 0.2]
 [-0.3]]
Iteration 1, Sample 1: Net Input: -0.5000
Error: 0.0000
Updated Weights:
[[ 0.4  0.3  0.2 -0.3]]


Final Weight Matrix:
 [[ 0.4]
 [ 0.3]
 [ 0.2]
 [-0.3]]
